### ISSUE TITLE
[Twitch] crash when stream goes offline

### ISSUE THREAD

**Issue by mlburggr** [mlburggr/OverRustleiOS#15]
This is pretty difficult to replicate, but when you try to connect to a Twitch stream that _just_ ended, the app crashes.

**Comment by hayksaakian** [comment]
the lines which parse individual qualities from the playlist throw the error
in my local builds i just return early, as soon as we have a playlist url

if/when we support a quality-picker this might become a problem

**Comment by mlburggr** [comment]
this seems to be fixed
